services:
  - type: web
    name: modbus-simulator
    runtime: python
    repo: https://github.com/prairie-spark-iot/modbus-simulator
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python -m src.main
    envVars:
      - key: PYTHON_VERSION
        value: 3.12
      - key: DEBUG
        value: true
    plan: free
    autoDeploy: true
    healthCheckPath: /
